// Copie française. Sarah relit ce fichier. Pas de tirets cadratins.
import type { Dictionary } from "./en"

export const fr: Dictionary = {
  meta: {
    title: "Sarah Henia, Ingénieure Solutions IA & Logiciel",
    description:
      "Sarah Henia conçoit des systèmes d'IA en production, où un humain valide chaque étape qui compte, avec la gouvernance pour le prouver. Études de cas : Dawn, un système de veille marché, Collaboris.",
  },
  nav: { work: "Réalisations", journey: "Parcours", about: "À propos", contact: "Contact", resume: "CV" },
  a11y: { skip: "Aller au contenu", theme: "Changer de thème", language: "Langue", menu: "Menu" },
  hero: {
    status: "Disponible · Tunis · mobilité internationale",
    name: "Sarah Henia",
    role: "Ingénieure Solutions IA & Logiciel",
    pitch: {
      before: "Je conçois des systèmes d'IA en production, où un ",
      accent: "humain",
      after: " valide chaque étape qui compte, avec la gouvernance pour le prouver.",
    },
    resume: "CV (PDF)",
    linkedin: "LinkedIn",
    github: "GitHub",
    email: "E-mail",
    photoAlt: "Portrait de Sarah Henia",
  },
  lens: {
    label: "Lire cette page en tant que",
    hint: "Mêmes faits, accent différent.",
    options: {
      sol: {
        label: "Solutions & gouvernance",
        summary:
          "Ingénieure solutions IA qui transforme des besoins métier en systèmes d'IA gouvernés et en production, et sait les expliquer aux ingénieurs comme aux dirigeants. A conçu la gouvernance de trois systèmes agentiques réels (RGPD, NIST AI RMF, ISO/IEC 42001), piloté une roadmap produit, et présente en français, anglais et arabe.",
        skills: [
          ["Solutions & produit", "Architecture de solution, expression de besoins et spécifications, roadmap et backlog, Agile/Scrum, gestion des parties prenantes, documentation technique, présentations aux dirigeants"],
          ["Gouvernance IA", "Passerelle IA, garde-fous, validation humaine, journalisation d'audit, évaluation et métriques LLM, RGPD, NIST AI RMF, ISO/IEC 42001"],
          ["IA & données", "IA agentique, systèmes multi-agents, LLM, RAG, CAG, mémoire en graphe, graphes de connaissances, MCP, ETL, CDC ; Azure OpenAI, OpenRouter ; SurrealDB, SQL Server, PostgreSQL, Redis, Cosmos DB"],
          ["Build & cloud", "Python, FastAPI, C#, ASP.NET Core, TypeScript, Angular, REST, passerelle d'API, API Microsoft Graph ; AWS, Azure, Docker, CI/CD, observabilité (Logfire, Langfuse)"],
        ],
      },
      ai: {
        label: "Ingénierie IA",
        summary:
          "Ingénieure IA qui conçoit et met en production des systèmes agentiques : pipelines LLM où un humain valide chaque écriture, graphes de connaissances et recherche hybride sur des données d'entreprise réelles, ainsi que les pipelines de données et l'infrastructure cloud qui les portent sur AWS et Azure, avec la gouvernance en tête.",
        skills: [
          ["IA", "Systèmes agentiques et multi-agents, LLM, RAG, CAG, mémoire en graphe, graphes de connaissances, MCP, passerelle IA, évaluation LLM, validation humaine, LangChain, Azure OpenAI, OpenRouter"],
          ["Données", "Modélisation, ETL, CDC, OLTP/OLAP, architecture medallion ; SurrealDB, PostgreSQL, SQL Server, MongoDB, Redis, Cosmos DB, Neo4j"],
          ["Développement", "Python, FastAPI, C#, ASP.NET Core, Node.js, TypeScript, Angular, React, REST, GraphQL, WebSockets, API Microsoft Graph"],
          ["Cloud & qualité", "AWS, Azure, Docker, GitHub Actions, CI/CD, Linux, observabilité (Logfire, Langfuse), pytest ; RGPD, NIST AI RMF, ISO/IEC 42001"],
        ],
      },
      swe: {
        label: "Ingénierie logicielle",
        summary:
          "Ingénieure logiciel issue du full-stack JavaScript (MERN), qui conçoit aujourd'hui des systèmes en production en C#/.NET, Angular et Python : une bibliothèque de présence temps réel pour l'entreprise, des pipelines de données et des agents IA déployés sur AWS et Azure. Attachée à un code que d'autres équipes peuvent installer, tester et maintenir.",
        skills: [
          ["Backend", "C#, ASP.NET Core, SignalR, Python, FastAPI, Node.js, Express, Django, REST, GraphQL, WebSockets, JWT, passerelle d'API"],
          ["Frontend", "TypeScript, JavaScript, Angular, React, Next.js, Tailwind CSS, API navigateur (MutationObserver, SharedWorker), UI/UX, Figma"],
          ["Données", "SQL Server, PostgreSQL, MongoDB, MySQL, Redis, Cosmos DB, SurrealDB ; ETL, CDC"],
          ["Cloud & DevOps", "Azure (App Service, pipelines DevOps), AWS EC2, Docker, GitHub Actions, CI/CD, Nginx, Linux, paquets npm et NuGet"],
        ],
      },
    },
  },
  work: {
    eyebrow: "Systèmes réalisés",
    heading: "Trois systèmes, chacun avec un humain dans la boucle",
    intro:
      "Ils vivent dans des dépôts d'entreprise privés, le code n'est donc pas public. Les histoires le sont : problème, architecture, décisions, gouvernance et ce que chacun m'a appris.",
    read: "Lire l'étude de cas",
    status: { live: "En production", pilot: "Pilote, en cours", shipped: "Livré, 3 releases" },
    cards: {
      architect: {
        title: "Architecte Logiciel & Intégratrice de Solutions IA",
        org: "The SamurAI · 2026 à aujourd'hui",
        text: "Conception du système de veille marché et de sa gouvernance : un graphe, une passerelle, un humain.",
      },
    },
  },
  earlier: {
    eyebrow: "Travaux antérieurs",
    heading: "Projets académiques, 2023 à 2025",
    intro: "Réalisés à ESPRIT, le plus souvent en équipe et en sprints. Plus modestes, mais c'est là que les habitudes se sont formées.",
    code: "Code",
    demo: "Démo",
    items: {
      sentinelhub: "Plateforme DevSecOps qui exécute plusieurs scanners de sécurité (Trivy, Semgrep, Gitleaks, SonarQube, OWASP ZAP) et affiche les résultats en temps réel avec Grafana.",
      taskify: "Application MERN de gestion de tâches et de projets avec priorisation assistée par Gemini, collaboration Socket.io et pipeline Docker plus GitHub Actions, construite en cinq sprints.",
      pentaart: "Plateforme d'art génératif combinant deux fournisseurs d'IA et de l'art algorithmique (fractales, champs de flux), traitements asynchrones avec Celery et Redis, galeries taguées.",
      brando: "Personnalisation 3D de t-shirts avec Three.js, module de sondages avec analytique, et automatisation Instagram pilotée par Gemini.",
      ecolink: "Suivi d'impact écologique et catégorisation des déchets par recherche sémantique, sur un backend Django et FastAPI avec un front Next.js.",
      waste2product: "Plateforme Laravel où l'on déclare des déchets, trouve des tutoriels de recyclage DIY et rejoint des événements environnementaux.",
    },
  },
  about: {
    eyebrow: "À propos",
    heading: "Ingénieure logiciel. Intégratrice de solutions IA.",
    paragraphs: [
      "Je conçois et construis des systèmes où un modèle propose, une personne décide et une base de données se souvient pourquoi. Aujourd'hui, c'est Dawn, en production depuis mars 2026, et le système de veille marché en pilote. Avant, c'était Collaboris, livré en trois releases chez CED Tunisia.",
      "Je suis venue au logiciel par les données : une licence en business intelligence d'abord, puis le génie logiciel à ESPRIT. Ça se voit dans ma façon de travailler. Ce qu'un chiffre veut dire compte autant pour moi que le code qui le produit, et j'écris le document d'architecture avant le premier commit.",
      "Je travaille sur toute la pile : Python et FastAPI, C# et .NET, Angular et TypeScript, SurrealDB, Redis et SQL Server, déployés sur AWS et Azure. Je présente en arabe, en anglais et en français, aux ingénieurs comme aux dirigeants.",
    ],
    facts: {
      location: ["Basée à", "Tunis, Tunisie · mobilité internationale"],
      languages: ["Langues", "Arabe (langue maternelle) · Anglais (C1) · Français (B2)"],
      education: ["Formation", "Diplôme d'ingénieur en génie logiciel, ESPRIT (2026) · Licence en business intelligence, ESSECT (2023)"],
      certs: ["Certifications", "Cisco CCNA (2024) · AWS Certified Cloud Practitioner (2025)"],
      nvidia: ["NVIDIA Deep Learning Institute (2025)", "Adversarial Machine Learning · Building RAG Agents with LLMs · Fundamentals of Deep Learning · Applications of AI for Predictive Maintenance"],
    },
  },
  contact: {
    eyebrow: "Contact",
    heading: "Parlons de ce que vous construisez",
    text: "Postes d'ingénierie solutions, gouvernance IA, ingénierie IA ou ingénierie logicielle. Europe, Moyen-Orient et Amériques.",
    copy: "Copier l'e-mail",
    copied: "Copié",
  },
  footer: {
    rights: "Sarah Henia",
    built: "Construit avec Next.js, déployé sur Vercel. Sans traceurs.",
    source: "Code du site",
  },
  caseLabels: {
    back: "Toutes les réalisations",
    role: "Mon rôle",
    period: "Période",
    status: "Statut",
    stack: "Technologies",
    resume: "Sur le CV",
    problem: "Le problème",
    built: "Ce que j'ai construit",
    architecture: "Comment ça marche",
    architectureHint: "Défile tout seul. Cliquez sur une étape pour faire pause.",
    decisions: "Décisions et compromis",
    governance: "Gouvernance",
    learned: "Ce que j'ai appris",
    next: "Étude de cas suivante",
    confidential: "Construit dans un dépôt d'entreprise privé. Noms, identifiants et références internes sont volontairement omis.",
  },
  cases: {
    dawn: {
      title: "Dawn",
      subtitle: "Un agent autonome de gestion de projet où rien n'est écrit avant qu'un humain ne l'approuve.",
      role: "Conception et développement de l'ensemble du système",
      period: "2026, en production depuis mars",
      status: "live",
      resume: [
        "Conçu et développé Dawn, un agent IA autonome de gestion de projet, mis en production en mars 2026 : transforme les réunions enregistrées en tâches (responsable, priorité, échéance), avec validation humaine avant toute écriture dans Microsoft Planner.",
        "Conçu sa mémoire en graphe : un graphe de connaissances SurrealDB avec RAG hybride (recherche vectorielle et pondération temporelle) et cache de contexte Redis (CAG), intégré à l'API Microsoft Graph.",
        "Conçu sa couche de gouvernance et de sécurité : contrôle d'identité, politiques par agent, messages entrants vérifiés par HMAC, journal d'audit, seuil de confiance et données sensibles routées vers un modèle Llama local.",
        "Développé un routage multi-modèles via OpenRouter avec repli automatique ; déployé sur AWS EC2 sécurisé avec CI/CD GitHub Actions et observabilité via Logfire et Langfuse.",
      ],
      problem: [
        "Une petite équipe de conseil enregistre beaucoup de réunions. Les engagements pris ne se transformaient pas de façon fiable en travail suivi : quelqu'un devait lire la transcription, décider qui fait quoi, et le saisir dans Microsoft Planner. Le suivi dépendait de la mémoire.",
        "La demande n'était pas « automatiser la gestion de projet ». Elle était plus étroite et plus dure : faire entrer les bonnes tâches dans Planner, avec le bon responsable et la bonne date, sans jamais laisser une IA écrire quelque chose que personne n'a vérifié.",
      ],
      built: [
        "Dawn lit les transcriptions, rassemble le contexte d'équipe nécessaire, extrait des tâches proposées avec responsable, priorité, échéance et score de confiance, et les envoie par e-mail à deux responsables. Ils répondent APPROVE ou REJECT. Alors seulement Dawn crée les tâches dans Planner, enregistre ce qui s'est passé dans sa mémoire en graphe, et commence à relancer les personnes quand le travail stagne.",
        "Microsoft bloquait les messages directs applicatifs dans Teams ; l'e-mail est donc devenu le canal de validation. Livré des semaines plus tôt qu'en attendant un accès administrateur, et les responsables l'ont adopté.",
      ],
      steps: [
        { id: "transcript", label: "Transcription", detail: "Les réunions enregistrées sont récupérées via l'API de l'enregistreur selon un planning, ou déposées comme fichiers dans un dossier surveillé. Chacune devient un enregistrement brut." },
        { id: "guard", label: "Garde-fou", detail: "Contrôles d'injection de prompt et de sensibilité avant qu'un modèle ne voie le texte. Les contenus réglementés ou sensibles pour un client sont routés vers un modèle Llama local et ne quittent jamais la machine." },
        { id: "context", label: "Contexte (CAG)", detail: "Effectif, charges de travail et règles apprises sont pré-assemblés dans Redis avec des TTL. Les petits faits stables sont mis en cache plutôt que recherchés." },
        { id: "memory", label: "Mémoire graphe (RAG)", detail: "Réunions et décisions passées vivent dans SurrealDB avec un index vectoriel. Les résultats sont reclassés par similarité et récence avec un seuil strict, pour que le bruit n'atteigne jamais le prompt." },
        { id: "extract", label: "Extraction", detail: "Un appel LLM propose des tâches : titre, responsable, catégorie, échéance, priorité, raisonnement et confiance. Les modèles sont des alias résolus par un routeur via OpenRouter avec repli automatique." },
        { id: "gate", label: "Seuil de confiance", detail: "Les propositions à haute confiance passent en revue, celles à confiance moyenne sont signalées, celles à faible confiance sont retenues et jamais proposées." },
        { id: "human", label: "Validation humaine", detail: "Les responsables reçoivent un e-mail de revue et répondent APPROVE ALL, APPROVE n ou REJECT n. La réponse est analysée par regex, puis LLM, puis humain. Rien n'est écrit avant cette étape.", gate: true },
        { id: "planner", label: "Planner", detail: "Les tâches approuvées sont créées dans Microsoft Planner via l'API Graph. Les refusées sont marquées résolues. Un e-mail de confirmation ferme la boucle." },
        { id: "writeback", label: "Réécriture", detail: "Chaque tâche créée devient des nœuds et arêtes du graphe (tâche, assignée à, extraite de), plus l'embedding du résumé de réunion. La mémoire grandit à chaque décision approuvée." },
        { id: "nudge", label: "Relances", detail: "Des exécutions planifiées rappellent les tâches en retard, publient un résumé de canal et une synthèse pour les responsables. On peut répondre « done » par e-mail. Silence quand tout va bien." },
      ],
      decisions: [
        ["Validation humaine avant toute écriture, plutôt que création automatique au-dessus d'un seuil", "La confiance devait venir d'abord, et le rayon d'impact d'une mauvaise tâche devait être nul. La règle livrée : rien n'atteint Planner sans réponse."],
        ["CAG et RAG, pas l'un ou l'autre", "Les petits faits stables sont en cache dans Redis. L'historique volumineux est recherché. Deux problèmes, deux outils."],
        ["Reclassement hybride plutôt que top-k naïf", "La similarité seule laissait de vieilles réunions dépasser les récentes. Similarité plus récence, avec seuil strict."],
        ["SurrealDB plutôt qu'une base graphe séparée plus un store vectoriel", "Documents, arêtes et vecteurs dans un moteur : un schéma, un client, une sauvegarde. Les arêtes sont de première classe."],
        ["Appels API directs plutôt qu'un framework d'agents", "Flux de contrôle explicite, appels IA lisibles, état visible dans Redis et SurrealDB."],
        ["Modèles comme alias derrière un routeur", "Changer de fournisseur tient en une ligne. Le contenu sensible est forcé vers un modèle local."],
        ["Archiver à 90 jours plutôt que supprimer", "L'historique a de la valeur et le stockage est bon marché."],
      ],
      governance: [
        ["Contrôle d'identité", "Seuls les expéditeurs du domaine de l'entreprise déclenchent des actions. Les externes sont redirigés sans données."],
        ["Messages entrants signés", "Chaque requête webhook Teams entrante est vérifiée par HMAC-SHA256. Les signatures invalides sont rejetées."],
        ["Routage des données sensibles", "Des mots-clés liés à des contenus réglementés ou sensibles forcent un modèle local et signalent l'élément."],
        ["Journal d'audit", "Chaque proposition garde son raisonnement, sa confiance, qui l'a résolue et quand. Les destinataires ne voient jamais les scores, les noms de modèles ou les identifiants."],
        ["Hôte durci", "Utilisateur de service non root, secrets hors dépôt, volume chiffré, IAM de moindre privilège, SSH par clé, correctifs automatiques. Déployé par GitHub Actions ; tracé dans Logfire et Langfuse."],
      ],
      learned: [
        "Chaque bug de production était un classique des systèmes distribués : doublons, boucle sur soi-même, mises à jour perdues. La solution était l'idempotence, pas un meilleur prompt.",
        "La validation humaine est une machine à états (en attente, approuvée, refusée, doublon, bloquée) et mérite autant de soin que l'appel au modèle.",
        "Un webhook qui doit répondre en cinq secondes et un traitement plus long sont deux programmes différents. Les séparer a supprimé toute une classe de plantages silencieux.",
        "La meilleure interface de validation était celle que les responsables utilisaient déjà. L'e-mail a battu l'interface sur mesure.",
      ],
    },
    "market-intelligence": {
      title: "Système de veille marché",
      subtitle: "Un système multi-agents qui lit le marché en anglais et en arabe et propose des pistes à un humain. Un graphe, une porte, un humain.",
      role: "Architecture, conception de la gouvernance et implémentation",
      period: "2026, pilote en cours",
      status: "pilot",
      resume: [
        "Conception et développement d'un système multi-agents de veille marché pour un client cybersécurité au Moyen-Orient : ingestion de données bilingue (anglais/arabe), classification et extraction LLM à schéma imposé vers un graphe de connaissances SurrealDB, avec revue humaine avant toute écriture CRM.",
        "Conception de sa gouvernance IA : une passerelle IA pour chaque appel de modèle ou d'outil (identité, budget, trace), contrôles alignés sur le NIST AI RMF et l'ISO/IEC 42001, et métriques d'évaluation sur un jeu annoté à chaque changement.",
      ],
      problem: [
        "Le client vend des services de cybersécurité et d'assurance IA dans le Golfe. Chaque jour des régulateurs agissent, des entreprises sont attaquées, des appels d'offres s'ouvrent. Personne ne peut tout lire, et la question est étroite : quelles entreprises de notre territoire viennent de faire quelque chose qui signifie qu'elles ont besoin de nous, et pourquoi ?",
        "Un scraper échoue parce qu'il produit des pages, pas des décisions. Un chatbot échoue parce qu'il peut inventer, ne s'audite pas, et pousserait des affirmations non vérifiées dans le CRM. Trois modes d'échec ont guidé la conception : un modèle qui invente, une entreprise présente deux fois dans les données, et des contrôles qui ne vivent que dans un prompt.",
      ],
      built: [
        "Le premier agent est un pipeline fixe, pas une boucle de raisonnement. Les sources en liste blanche sont récupérées et normalisées en anglais et en arabe. Un appel LLM par article renvoie « non pertinent » ou une fiche typée : entreprise telle que nommée, type d'événement et pilier issus de listes fermées, date, citation exacte, raison d'appeler, confiance. Le code vérifie ensuite que la citation existe dans l'article ; sinon la fiche est mise en quarantaine, quoi qu'ait dit le modèle.",
        "Les fiches vérifiées sont rapprochées du graphe de comptes et arrivent dans une file de revue où un relecteur nommé approuve, modifie ou refuse avec un motif. Seule une approbation déclenche l'écriture CRM, via un petit outil qui détient l'unique identifiant d'intégration. L'agent ne le détient jamais.",
        "État en octobre 2026 : ingestion et normalisation tournent sur de vraies sources ; extraction et vérification sont construites et en revue ; rapprochement d'entreprises, file de revue et écriture CRM sont les prochaines étapes ; un jeu d'évaluation annoté se constitue à partir des décisions des relecteurs.",
      ],
      steps: [
        { id: "sources", label: "Sources", detail: "Une table de liste blanche détenue par le métier, pas une ligne de prompt. Le marketing approuve chaque source avant activation. Un prompt peut être ignoré ou injecté ; une table lue par le collecteur, non.", gate: true },
        { id: "ingest", label: "Ingestion", detail: "Flux d'abord, pages de listing ensuite, liens du même site seulement. Chaque élément est stocké tel quel avec URL, horodatage et hash de contenu comme identifiant. Les échecs sont mis en quarantaine avec un motif, jamais perdus." },
        { id: "normalize", label: "Normalisation", detail: "La langue est décidée de façon déterministe en comptant lettres arabes et latines, car la détection standard était aléatoire sur les textes courts. Tout est dérivé de l'élément brut, donc rejouable." },
        { id: "extract", label: "Classification + extraction", detail: "Un appel LLM via la passerelle renvoie le schéma ou rien : entreprise, type d'événement et pilier depuis des listes fermées, date, citation exacte, raison d'appeler, confiance. Le texte de l'article passe en dernier et est traité comme non fiable." },
        { id: "verify", label: "Vérification par le code", detail: "Une fiche dont la citation ou le nom d'entreprise n'est pas dans le texte est rejetée par le code. L'hallucination est arrêtée par un contrôle, pas par un prompt." },
        { id: "graph", label: "Graphe de connaissances", detail: "SurrealDB contient organisations, personnes, sources, éléments, signaux, piliers et décisions. Chaque relation est une arête, jamais un champ : « non résolu » est simplement l'absence d'arête." },
        { id: "resolve", label: "Rapprochement", detail: "Nom normalisé et alias comparés aux comptes connus. Sans correspondance, un candidat est créé, jamais un nœud canonique. Le code ne fusionne jamais deux organisations ; un humain le fait." },
        { id: "review", label: "Revue humaine", detail: "Un relecteur nommé approuve, modifie ou refuse chaque fiche avec un motif obligatoire. Chaque clic devient une décision dans le graphe et, plus tard, un exemple annoté.", gate: true },
        { id: "crm", label: "Écriture CRM", detail: "Un petit outil détenant l'unique identifiant CRM crée la piste, et seulement sur approbation. Rien n'atteint le CRM sans un clic." },
      ],
      decisions: [
        ["Un seul store pour documents, graphe et vecteurs", "Plutôt qu'une base vectorielle plus une base graphe plus un store documentaire : un schéma, un client, une sauvegarde. Le coût : un moteur jeune, donc test de charge avant la production."],
        ["Chaque relation est une arête, jamais un champ", "Un fait stocké deux fois finit par se contredire. Les métadonnées de correspondance vivent sur l'arête."],
        ["Un LLM classe et extrait pour le pilote", "Entraîner un petit classifieur aurait exigé des données annotées inexistantes. Le pilote produit la première vraie fiche des semaines plus tôt, et les décisions des relecteurs deviennent le jeu annoté."],
        ["Une commande planifiée plutôt qu'un moteur de workflow", "Une vingtaine de sources, une ligne droite, chaque étape testable. L'attente humaine est hors du pipeline."],
        ["Le code demande un surnom de modèle, jamais un fournisseur", "La passerelle associe le surnom à un modèle avec repli. Le modèle est choisi par son score sur les fiches annotées, pas par sa marque."],
        ["Exactement une interface légère", "La file de revue est le seul écran construit pour le pilote."],
      ],
      governance: [
        ["Une porte : la passerelle IA", "L'application détient une clé de passerelle ; les clés des fournisseurs ne vivent que dans la passerelle. Elle gère le repli, réessaie une fois, expire, compte les jetons contre un budget par exécution et enregistre le modèle réel derrière chaque appel. Un test de frontière impose qu'un seul fichier puisse appeler un modèle."],
        ["NIST AI RMF", "Govern : un propriétaire par agent et un dossier de décision par choix. Map : texte collecté traité comme non fiable, listes fermées, registre de risques. Measure : le jeu d'évaluation. Manage : portes humaines en entrée et en sortie, quarantaine, conditions d'arrêt."],
        ["ISO/IEC 42001", "La politique comme donnée (table des sources, table des piliers). Piste d'audit dans le graphe de la fiche à l'élément à la source, avec versions de prompt et de modèle, relecteur et motif."],
        ["Règles régionales", "Lignes directrices régionales en IA et protection des données traduites en supervision humaine, zone de données locale et enrichissement contrôlé des données personnelles."],
        ["Évaluation à chaque changement", "Un jeu versionné de fiches annotées rejoué à chaque changement de prompt, de modèle ou de liste de sources. Métriques : précision, exactitude du rapprochement, coût par exécution, avec rappel et fidélité proposés."],
      ],
      learned: [
        "L'IA occupe deux cases, un humain en occupe une, et du code ordinaire et une base de données font tout le reste. La fiabilité est venue du code ordinaire.",
        "L'application du schéma doit vivre à trois niveaux : assertions en base, modèles typés qui les reflètent avec un test de dérive, et extraction qui renvoie le schéma ou rien.",
        "Les vraies sources se comportent mal : protections anti-bot, coquilles JavaScript, PDF, dates peu fiables. La quarantaine avec motif vaut mieux que l'oubli silencieux.",
        "Un client de base qui ne lève pas d'erreur sur une instruction échouée dans une transaction vous apprend à lire le statut de chaque instruction. Une fois.",
      ],
    },
    collaboris: {
      title: "Collaboris",
      subtitle: "Une bibliothèque de présence temps réel pour applications web d'entreprise, avec un journal conforme RGPD dès la conception et un assistant IA gouverné.",
      role: "De bout en bout : architecture, implémentation, packaging, déploiement, présentation aux dirigeants",
      period: "Février à août 2026, trois releases",
      status: "shipped",
      resume: [
        "Développé Collaboris, une bibliothèque de présence temps réel pour applications web d'entreprise, livrée en deux paquets : une bibliothèque Angular 19 (npm) et un SDK ASP.NET Core 8 (NuGet) sur SignalR et Redis. Trois releases sous revue technique du chef de département.",
        "Présenté l'architecture, la gouvernance et l'intérêt métier au chef de département et aux dirigeants de CED.",
        "Conçu une cascade d'identification à cinq niveaux qui reconnaît l'utilisateur depuis la session existante de l'application hôte, sans double connexion.",
        "Conçu un résolveur de vue en couches : un MutationObserver DOM ciblé et temporisé qui situe chaque utilisateur jusqu'au dialogue, onglet ou étape ouverts, pour une co-présence exacte.",
        "Détecté l'activité réelle en interceptant fetch et XMLHttpRequest (méthodes d'écriture uniquement, liste d'exclusion, fenêtre de déduplication) et mutualisé tous les onglets sur un seul WebSocket via un SharedWorker.",
        "Développé PresenceAI, la couche données et IA : capture de changements des signaux Redis vers un journal Cosmos DB (OLTP vers OLAP, Python/FastAPI), interrogé en langage naturel via un assistant Azure OpenAI gouverné, exposé en MCP.",
        "Mis en œuvre la conformité RGPD dès la conception (minimisation, consentement, rétention de 30 jours par TTL, accès fermé par défaut, plafonds de coût) et couvert la couche IA par des tests unitaires.",
        "Déployé l'ensemble sur Azure (App Service, SQL Server, Azure Cache for Redis) via les pipelines build et release Azure DevOps, avec migration de la couche de données de l'API de PostgreSQL vers SQL Server.",
      ],
      problem: [
        "Deux gestionnaires de sinistres ouvrent le même dossier dans une application interne au même moment. Aucun ne sait que l'autre est là. Le premier enregistre. Le second, à partir de ce qu'il voyait un instant plus tôt, enregistre aussi et écrase silencieusement le premier. Pas d'alerte, pas de conflit. Le dernier enregistrement gagne, et personne ne le remarque avant un client.",
        "Les applications web d'entreprise sont aveugles à leurs propres utilisateurs. La question : rendre n'importe quelle application interne consciente de qui s'y trouve et de ce qui change, sans la reconstruire, et sans que ces données deviennent un outil de surveillance.",
      ],
      built: [
        "Collaboris est une bibliothèque prête à l'emploi : l'application Angular hôte installe un paquet npm, son backend ajoute un paquet NuGet, et un bloc de configuration relie le tout. Les utilisateurs voient qui est présent, jusqu'au dialogue, à l'onglet ou à l'étape ouverts, et sont prévenus quand la donnée sous leurs yeux change. L'identité vient de la session existante de l'hôte.",
        "La release 3 a ajouté PresenceAI : le flux éphémère de présence est capturé dans un journal durable et à rétention bornée dans Cosmos DB, et des managers autorisés peuvent l'interroger en langage naturel via un assistant Azure OpenAI gouverné, aussi exposé en MCP. Redis contient ce qui se passe ; Cosmos ce qui s'est passé.",
        "Tout a été livré sous forme de vrais paquets, installés par l'hôte comme un client le ferait, et déployé sur Azure via les pipelines Azure DevOps.",
      ],
      steps: [
        { id: "tabs", label: "Onglets", detail: "Dans l'application hôte, la bibliothèque résout l'identité par une cascade à cinq niveaux et dérive la position de l'utilisateur comme une chaîne de vues ordonnée : route, modale, onglet, mode. Deux utilisateurs sont « ensemble » seulement si leurs chaînes sont strictement égales. L'URL ment dans une application monopage." },
        { id: "worker", label: "SharedWorker", detail: "Un WebSocket par navigateur. Les onglets s'y attachent par ports de message, chacun avec son propre enregistrement : dix onglets coûtent une connexion, fermer un onglet signifie exactement une chose." },
        { id: "hub", label: "Hub SignalR", detail: "Le SDK ASP.NET Core s'authentifie avec le jeton de l'hôte et diffuse d'abord, persiste ensuite. Le temps réel n'attend jamais le stockage." },
        { id: "redis", label: "Redis", detail: "Un enregistrement par onglet avec un TTL renouvelé par le battement de cœur, et quatre couches contre les fantômes : désinscription explicite, gestion de déconnexion, minuteries d'obsolescence, filet TTL. Le silence retire un utilisateur." },
        { id: "activity", label: "Détection d'activité", detail: "fetch et XMLHttpRequest sont interceptés pour les méthodes d'écriture seulement, avec liste d'exclusion et fenêtre de déduplication. Le verbe est une affirmation, pas une vérité : une réponse de succès est requise avant de notifier. Des règles d'équité plafonnent les notifications et regroupent les rafales." },
        { id: "cdc", label: "Capture de changements", detail: "Les événements d'espace de clés Redis sont consommés par un service Python indépendant. Le chemin opérationnel n'attend jamais le chemin analytique." },
        { id: "journal", label: "Journal (OLTP vers OLAP)", detail: "Une session n'est écrite que si une mutation a eu lieu : la lecture pure ne laisse aucune trace. Les URL sont normalisées en vocabulaire métier, les agrégats calculés à l'écriture, et chaque enregistrement porte un TTL de 30 jours." },
        { id: "ai", label: "IA gouvernée", detail: "Liste blanche fermée par défaut, puis classifieur à trois niveaux : les questions d'activité sont répondues, celles sur une personne nommée sont reformulées au niveau équipe, et les questions de jugement, de prédiction ou RH sont refusées sans condition. Chaque interaction, refus compris, est auditée. La même surface est exposée en MCP.", gate: true },
      ],
      decisions: [
        ["Deux stores plutôt qu'un", "Le temps réel veut des lectures en microsecondes et un état éphémère ; l'analytique veut de l'historique et des agrégats. Redis et Cosmos DB, reliés par un pipeline que le chemin direct n'attend jamais."],
        ["Un pipeline déterministe plutôt qu'un journal construit par LLM", "Coût, reproductibilité et confiance. Le même historique produit toujours le même journal. Le modèle ne vit qu'aux bords."],
        ["Synthèse de session à l'écriture", "Plutôt que tout refléter puis supprimer, le pipeline décide à l'ingestion ce qui mérite d'exister. Le stockage est borné par construction, ce que le RGPD demande aussi."],
        ["Une liste blanche plutôt que les rôles de l'hôte pour l'accès IA", "La sémantique des rôles ne voyage pas entre pays et applications. Le propriétaire de chaque application déclare qui peut interroger ; par défaut, personne."],
        ["L'hôte authentifie, la bibliothèque lit", "Le schéma JWT propre au SDK a été retiré en revue d'intégration : une bibliothèque ne peut pas posséder la politique de sécurité de son hôte. Retirer est un acte de conception."],
        ["Génération augmentée par cache plutôt que recherche", "Le journal est petit par construction ; les résumés récents tiennent dans le contexte. Pas d'infrastructure vectorielle."],
        ["Python et FastAPI pour la couche IA dans une maison .NET", "Consommation de flux asynchrone, validation typée, streaming natif et écosystème IA, en service déployable indépendamment."],
      ],
      governance: [
        ["Minimisation des données", "Coordonnées du travail seulement : identité, position, statut, événements de changement. Jamais de contenu, de valeurs de formulaire ni de frappes."],
        ["Consentement", "Explicite, éclairé et révocable, recueilli avant tout suivi ; un écran de confirmation d'identité montre ce qui sera partagé."],
        ["Rétention par le schéma", "TTL de 30 jours sur les enregistrements fins, appliqué par la base elle-même. Ce qui n'a jamais été écrit ne peut pas fuir."],
        ["Surveillance impossible par construction", "Le journal stocke des comptages, pas des évaluations individuelles. Les questions de jugement et de prédiction sur des personnes sont refusées par conception."],
        ["Accès fermé par défaut et plafonds de coût", "Pas d'entrée dans la liste, pas d'accès. Plafonds par question et mensuels sur la couche IA."],
        ["Registre des traitements", "Chaque question, classification, réponse et refus est journalisé. La couche IA est couverte par des tests unitaires."],
      ],
      learned: [
        "Ne jamais croire la santé auto-déclarée d'un composant. Le bug le plus dur : une connexion qui se disait saine alors que sa réception était morte ; la solution a été de suivre l'âge du dernier message reçu.",
        "L'auteur d'une bibliothèque ne contrôle rien : ni les habitudes de l'hôte, ni son stockage, ni son déploiement. Concevoir pour cela est une autre discipline que construire une application.",
        "Comparer d'abord. Chaque composant a commencé par la façon dont l'industrie résout déjà le problème, et le jour où l'état de l'art s'est tu, j'ai su quelle partie du projet était la mienne.",
        "Retirer est un acte de conception. Un moteur de vues heuristique, un classeur de sévérité, un chemin de stockage graphe et la couche d'authentification du SDK ont été construits, évalués et supprimés, chacun argumenté par écrit.",
      ],
    },
  },
}
